version: "3.8"

# notes:
# "ports SOME_PUBLICPORT:SOME_INTERNALPORT" sets up a forwarding from host (aka ouside world) to internal docker network
# "expose SOME_INTERNALPORT" is only for documentation / metadata on the container. set this to the port that the service is using.
# communicate between services with protocol://servicename:INTERNALPORT eg http://api:3002 or mysql://someusername:somepassword@db:3306/db

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT_EXPOSED:$MYSQL_PORT
    expose:
      - $MYSQL_PORT
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
  api:
    image: andersgee/howler-api
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: $DATABASE_URL_CONTAINER
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - $API_PORT:$API_PORT
    expose:
      - $API_PORT

volumes:
  db-data:
