version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT_EXPOSED:$MYSQL_PORT
    expose:
      - $MYSQL_PORT_EXPOSED
    volumes:
      - db-data:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
  api:
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      DATABASE_URL: $DATABASE_URL_CONTAINER
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - $API_PORT:$API_PORT
    expose:
      - $API_PORT

volumes:
  db-data:
